// src/services/playerDatabase.js

// This simulates the JSON data we would receive from our future Python/API backend.
// FILTERS APPLIED: >8.0 MPG, >2 Years Experience.

export const REAL_PLAYER_DB = [
    // ==========================================
    // TIER 5: SUPERSTARS ($5) - Avg FP > 50
    // ==========================================
    { id: 1001, name: "Nikola Jokic", team: "DEN", avgFP: 58.2, cost: 5, avatar: "🃏" },
    { id: 1002, name: "Luka Doncic", team: "DAL", avgFP: 56.8, cost: 5, avatar: "🪄" },
    { id: 1003, name: "Joel Embiid", team: "PHI", avgFP: 59.1, cost: 5, avatar: "🔔" },
    { id: 1004, name: "Giannis Antetokounmpo", team: "MIL", avgFP: 55.4, cost: 5, avatar: "🦌" },
    { id: 1005, name: "Shai Gilgeous-Alexander", team: "OKC", avgFP: 52.3, cost: 5, avatar: "⚡" },
    { id: 1006, name: "Anthony Davis", team: "LAL", avgFP: 51.0, cost: 5, avatar: "〰️" },
    { id: 1007, name: "Domantas Sabonis", team: "SAC", avgFP: 50.5, cost: 5, avatar: "🐂" },
    { id: 1008, name: "Victor Wembanyama", team: "SAS", avgFP: 52.0, cost: 5, avatar: "👽" }, // Sophomore exception applied
    { id: 1009, name: "Jayson Tatum", team: "BOS", avgFP: 50.1, cost: 5, avatar: "🍀" },
  
    // ==========================================
    // TIER 4: ALL-STARS ($4) - Avg FP 40-49
    // ==========================================
    { id: 2001, name: "LeBron James", team: "LAL", avgFP: 48.5, cost: 4, avatar: "👑" },
    { id: 2002, name: "Stephen Curry", team: "GSW", avgFP: 47.2, cost: 4, avatar: "🎯" },
    { id: 2003, name: "Kevin Durant", team: "PHX", avgFP: 46.8, cost: 4, avatar: "🐍" },
    { id: 2004, name: "Tyrese Haliburton", team: "IND", avgFP: 45.4, cost: 4, avatar: "🚧" },
    { id: 2005, name: "Donovan Mitchell", team: "CLE", avgFP: 44.9, cost: 4, avatar: "🕷️" },
    { id: 2006, name: "Trae Young", team: "ATL", avgFP: 44.2, cost: 4, avatar: "❄️" },
    { id: 2007, name: "Devin Booker", team: "PHX", avgFP: 43.8, cost: 4, avatar: "☀️" },
    { id: 2008, name: "Anthony Edwards", team: "MIN", avgFP: 43.5, cost: 4, avatar: "🐜" },
    { id: 2009, name: "De'Aaron Fox", team: "SAC", avgFP: 42.9, cost: 4, avatar: "🦊" },
    { id: 2010, name: "Kyrie Irving", team: "DAL", avgFP: 42.1, cost: 4, avatar: "👁️" },
    { id: 2011, name: "Bam Adebayo", team: "MIA", avgFP: 41.5, cost: 4, avatar: "🔥" },
    { id: 2012, name: "Damian Lillard", team: "MIL", avgFP: 41.2, cost: 4, avatar: "⌚" },
    { id: 2013, name: "LaMelo Ball", team: "CHA", avgFP: 40.8, cost: 4, avatar: "🛸" },
    { id: 2014, name: "Ja Morant", team: "MEM", avgFP: 44.0, cost: 4, avatar: "🥷" },
    { id: 2015, name: "Kawhi Leonard", team: "LAC", avgFP: 40.5, cost: 4, avatar: "🤚" },
    { id: 2016, name: "James Harden", team: "LAC", avgFP: 40.2, cost: 4, avatar: "🧔" },
  
    // ==========================================
    // TIER 3: STARTERS ($3) - Avg FP 30-39
    // ==========================================
    { id: 3001, name: "Jaylen Brown", team: "BOS", avgFP: 38.5, cost: 3, avatar: "☘️" },
    { id: 3002, name: "Jalen Brunson", team: "NYK", avgFP: 39.2, cost: 3, avatar: "🗽" },
    { id: 3003, name: "Tyrese Maxey", team: "PHI", avgFP: 38.0, cost: 3, avatar: "💎" },
    { id: 3004, name: "Alperen Sengun", team: "HOU", avgFP: 37.5, cost: 3, avatar: "🚀" },
    { id: 3005, name: "Zion Williamson", team: "NOP", avgFP: 36.8, cost: 3, avatar: "💪" },
    { id: 3006, name: "Scottie Barnes", team: "TOR", avgFP: 39.5, cost: 3, avatar: "🦖" },
    { id: 3007, name: "Paul George", team: "PHI", avgFP: 39.0, cost: 3, avatar: "🎒" },
    { id: 3008, name: "Chet Holmgren", team: "OKC", avgFP: 35.5, cost: 3, avatar: "📏" },
    { id: 3009, name: "Jimmy Butler", team: "MIA", avgFP: 37.2, cost: 3, avatar: "☕" },
    { id: 3010, name: "Luri Markkanen", team: "UTA", avgFP: 36.5, cost: 3, avatar: "🇫🇮" },
    { id: 3011, name: "Dejounte Murray", team: "NOP", avgFP: 38.8, cost: 3, avatar: "🦅" },
    { id: 3012, name: "Pascal Siakam", team: "IND", avgFP: 36.2, cost: 3, avatar: "🌶️" },
    { id: 3013, name: "Karl-Anthony Towns", team: "NYK", avgFP: 38.5, cost: 3, avatar: "😼" },
    { id: 3014, name: "Evan Mobley", team: "CLE", avgFP: 34.5, cost: 3, avatar: "🛡️" },
    { id: 3015, name: "Mikal Bridges", team: "NYK", avgFP: 33.2, cost: 3, avatar: "🌉" },
    { id: 3016, name: "Franz Wagner", team: "ORL", avgFP: 34.0, cost: 3, avatar: "🎹" },
    { id: 3017, name: "Cade Cunningham", team: "DET", avgFP: 35.8, cost: 3, avatar: "🏎️" },
    { id: 3018, name: "Desmond Bane", team: "MEM", avgFP: 36.0, cost: 3, avatar: "💪" },
    { id: 3019, name: "Jaren Jackson Jr.", team: "MEM", avgFP: 35.5, cost: 3, avatar: "🦄" },
    { id: 3020, name: "Myles Turner", team: "IND", avgFP: 31.5, cost: 3, avatar: "🧱" },
    { id: 3021, name: "Julius Randle", team: "MIN", avgFP: 37.0, cost: 3, avatar: "🦁" },
    { id: 3022, name: "Fred VanVleet", team: "HOU", avgFP: 34.0, cost: 3, avatar: "🎲" },
    { id: 3023, name: "Brandon Ingram", team: "NOP", avgFP: 35.0, cost: 3, avatar: "🦒" },
    { id: 3024, name: "Kristaps Porzingis", team: "BOS", avgFP: 33.5, cost: 3, avatar: "🦄" },
    { id: 3025, name: "Derrick White", team: "BOS", avgFP: 30.5, cost: 3, avatar: "🐃" },
    { id: 3026, name: "Jamal Murray", team: "DEN", avgFP: 34.8, cost: 3, avatar: "🏹" },
    { id: 3027, name: "Rudy Gobert", team: "MIN", avgFP: 32.5, cost: 3, avatar: "🗼" },
  
    // ==========================================
    // TIER 2: ROTATION ($2) - Avg FP 20-29
    // ==========================================
    { id: 4001, name: "Austin Reaves", team: "LAL", avgFP: 28.5, cost: 2, avatar: "🎸" },
    { id: 4002, name: "D'Angelo Russell", team: "LAL", avgFP: 29.5, cost: 2, avatar: "🧊" },
    { id: 4003, name: "Jrue Holiday", team: "BOS", avgFP: 29.0, cost: 2, avatar: "🛡️" },
    { id: 4004, name: "Aaron Gordon", team: "DEN", avgFP: 27.5, cost: 2, avatar: "🔨" },
    { id: 4005, name: "Michael Porter Jr.", team: "DEN", avgFP: 28.8, cost: 2, avatar: "🏹" },
    { id: 4006, name: "CJ McCollum", team: "NOP", avgFP: 29.8, cost: 2, avatar: "🍷" },
    { id: 4007, name: "Klay Thompson", team: "DAL", avgFP: 26.5, cost: 2, avatar: "⛵" },
    { id: 4008, name: "Draymond Green", team: "GSW", avgFP: 27.2, cost: 2, avatar: "🥊" },
    { id: 4009, name: "Malik Monk", team: "SAC", avgFP: 26.0, cost: 2, avatar: "🔦" },
    { id: 4010, name: "Naz Reid", team: "MIN", avgFP: 25.5, cost: 2, avatar: "🐺" },
    { id: 4011, name: "Josh Hart", team: "NYK", avgFP: 28.2, cost: 2, avatar: "❤️" },
    { id: 4012, name: "OG Anunoby", team: "NYK", avgFP: 27.0, cost: 2, avatar: "🧣" },
    { id: 4013, name: "Herbert Jones", team: "NOP", avgFP: 23.5, cost: 2, avatar: "🔒" },
    { id: 4014, name: "Brook Lopez", team: "MIL", avgFP: 25.0, cost: 2, avatar: "🏔️" },
    { id: 4015, name: "Jonas Valanciunas", team: "WAS", avgFP: 28.0, cost: 2, avatar: "🇱🇹" },
    { id: 4016, name: "Bradley Beal", team: "PHX", avgFP: 29.0, cost: 2, avatar: "🐼" },
    { id: 4017, name: "Clint Capela", team: "ATL", avgFP: 26.8, cost: 2, avatar: "🇨🇭" },
    { id: 4018, name: "John Collins", team: "UTA", avgFP: 27.5, cost: 2, avatar: "🛫" },
    { id: 4019, name: "Bobby Portis", team: "MIL", avgFP: 24.5, cost: 2, avatar: "🤪" },
    { id: 4020, name: "Ivica Zubac", team: "LAC", avgFP: 28.5, cost: 2, avatar: "🇭🇷" },
    { id: 4021, name: "Tobias Harris", team: "DET", avgFP: 28.0, cost: 2, avatar: "📚" },
    { id: 4022, name: "Jarrett Allen", team: "CLE", avgFP: 29.5, cost: 2, avatar: "🧶" },
    { id: 4023, name: "RJ Barrett", team: "TOR", avgFP: 29.2, cost: 2, avatar: "🍁" },
    { id: 4024, name: "Immanuel Quickley", team: "TOR", avgFP: 28.5, cost: 2, avatar: "⚡" },
    { id: 4025, name: "Jerami Grant", team: "POR", avgFP: 29.5, cost: 2, avatar: "🦁" },
    { id: 4026, name: "Anfernee Simons", team: "POR", avgFP: 29.0, cost: 2, avatar: "🐜" },
    { id: 4027, name: "Kyle Kuzma", team: "WAS", avgFP: 29.8, cost: 2, avatar: "🧥" },
    { id: 4028, name: "Terry Rozier", team: "MIA", avgFP: 28.5, cost: 2, avatar: "👻" },
    { id: 4029, name: "Tyler Herro", team: "MIA", avgFP: 29.5, cost: 2, avatar: "👶" },
    { id: 4030, name: "Chris Paul", team: "SAS", avgFP: 26.5, cost: 2, avatar: "👴" },
  
    // ==========================================
    // TIER 1: BENCH / ROLE PLAYERS ($1) - Avg FP < 20
    // ==========================================
    { id: 5001, name: "Jose Alvarado", team: "NOP", avgFP: 18.5, cost: 1, avatar: "🥑" },
    { id: 5002, name: "Alex Caruso", team: "OKC", avgFP: 19.5, cost: 1, avatar: "🚕" },
    { id: 5003, name: "Kentavious Caldwell-Pope", team: "ORL", avgFP: 18.2, cost: 1, avatar: "🏹" },
    { id: 5004, name: "Al Horford", team: "BOS", avgFP: 19.8, cost: 1, avatar: "👴" },
    { id: 5005, name: "Payton Pritchard", team: "BOS", avgFP: 16.5, cost: 1, avatar: "👟" },
    { id: 5006, name: "Sam Hauser", team: "BOS", avgFP: 12.5, cost: 1, avatar: "🎯" },
    { id: 5007, name: "Christian Braun", team: "DEN", avgFP: 15.5, cost: 1, avatar: "💪" },
    { id: 5008, name: "Peyton Watson", team: "DEN", avgFP: 14.2, cost: 1, avatar: "🛡️" },
    { id: 5009, name: "Gabe Vincent", team: "LAL", avgFP: 13.5, cost: 1, avatar: "⚓" },
    { id: 5100, name: "Rui Hachimura", team: "LAL", avgFP: 19.5, cost: 1, avatar: "⚔️" },
    { id: 5011, name: "Jarred Vanderbilt", team: "LAL", avgFP: 16.0, cost: 1, avatar: "🔒" },
    { id: 5012, name: "Jonathan Isaac", team: "ORL", avgFP: 19.2, cost: 1, avatar: "⛪" },
    { id: 5013, name: "Gary Harris", team: "ORL", avgFP: 14.5, cost: 1, avatar: "🛡️" },
    { id: 5014, name: "Cole Anthony", team: "ORL", avgFP: 18.8, cost: 1, avatar: "🥶" },
    { id: 5015, name: "Kyle Anderson", team: "GSW", avgFP: 18.5, cost: 1, avatar: "🐢" },
    { id: 5016, name: "Buddy Hield", team: "GSW", avgFP: 19.8, cost: 1, avatar: "🥥" },
    { id: 5017, name: "Gary Payton II", team: "GSW", avgFP: 14.0, cost: 1, avatar: "🧤" },
    { id: 5018, name: "P.J. Tucker", team: "LAC", avgFP: 10.5, cost: 1, avatar: "👟" },
    { id: 5019, name: "Norman Powell", team: "LAC", avgFP: 19.9, cost: 1, avatar: "🏹" },
    { id: 5020, name: "Terance Mann", team: "LAC", avgFP: 17.5, cost: 1, avatar: "🏃" },
    { id: 5021, name: "Obi Toppin", team: "IND", avgFP: 17.8, cost: 1, avatar: "✈️" },
    { id: 5022, name: "T.J. McConnell", team: "IND", avgFP: 19.5, cost: 1, avatar: "🐜" },
    { id: 5023, name: "Isaiah Jackson", team: "IND", avgFP: 15.0, cost: 1, avatar: "⛔" },
    { id: 5024, name: "Kevin Love", team: "MIA", avgFP: 16.5, cost: 1, avatar: "👴" },
    { id: 5025, name: "Jaime Jaquez Jr.", team: "MIA", avgFP: 19.2, cost: 1, avatar: "🇲🇽" },
    { id: 5026, name: "Duncan Robinson", team: "MIA", avgFP: 15.5, cost: 1, avatar: "🍩" },
    { id: 5027, name: "Haywood Highsmith", team: "MIA", avgFP: 13.0, cost: 1, avatar: "🔒" },
    { id: 5028, name: "Caris LeVert", team: "CLE", avgFP: 19.5, cost: 1, avatar: "🩹" },
    { id: 5029, name: "Isaac Okoro", team: "CLE", avgFP: 14.5, cost: 1, avatar: "🧊" },
    { id: 5030, name: "Georges Niang", team: "CLE", avgFP: 12.0, cost: 1, avatar: "🚐" },
    { id: 5031, name: "Andre Drummond", team: "PHI", avgFP: 19.0, cost: 1, avatar: "🦍" },
    { id: 5032, name: "Eric Gordon", team: "PHI", avgFP: 15.5, cost: 1, avatar: "☄️" },
    { id: 5033, name: "Kelly Oubre Jr.", team: "PHI", avgFP: 19.8, cost: 1, avatar: "🌊" },
    { id: 5034, name: "Pat Connaughton", team: "MIL", avgFP: 14.0, cost: 1, avatar: "⚾" },
    { id: 5035, name: "Delon Wright", team: "MIL", avgFP: 13.5, cost: 1, avatar: "🎮" },
    { id: 5036, name: "Dorian Finney-Smith", team: "BKN", avgFP: 18.5, cost: 1, avatar: "🦈" },
    { id: 5037, name: "Cam Johnson", team: "BKN", avgFP: 19.8, cost: 1, avatar: "🌧️" },
    { id: 5038, name: "Dennis Schroder", team: "BKN", avgFP: 19.5, cost: 1, avatar: "🇩🇪" },
    { id: 5039, name: "Ben Simmons", team: "BKN", avgFP: 18.0, cost: 1, avatar: "😤" },
    { id: 5040, name: "Precious Achiuwa", team: "NYK", avgFP: 16.5, cost: 1, avatar: "🦁" },
    { id: 5041, name: "Miles McBride", team: "NYK", avgFP: 15.0, cost: 1, avatar: "🐕" },
    { id: 5042, name: "Mitchell Robinson", team: "NYK", avgFP: 19.5, cost: 1, avatar: "🏗️" },
    { id: 5043, name: "Bogdan Bogdanovic", team: "ATL", avgFP: 19.8, cost: 1, avatar: "🇷🇸" },
    { id: 5044, name: "Larry Nance Jr.", team: "ATL", avgFP: 17.0, cost: 1, avatar: "✈️" },
    { id: 5045, name: "Dyson Daniels", team: "ATL", avgFP: 15.5, cost: 1, avatar: "🇦🇺" },
    { id: 5046, name: "Grant Williams", team: "CHA", avgFP: 16.0, cost: 1, avatar: "🦇" },
    { id: 5047, name: "Nick Richards", team: "CHA", avgFP: 18.0, cost: 1, avatar: "🇯🇲" },
    { id: 5048, name: "Caleb Martin", team: "PHI", avgFP: 17.5, cost: 1, avatar: "🔥" },
    { id: 5049, name: "Kevin Huerter", team: "SAC", avgFP: 18.5, cost: 1, avatar: "🔴" },
    { id: 5050, name: "Trey Lyles", team: "SAC", avgFP: 14.5, cost: 1, avatar: "🍁" }
  ];